
export const TYPING_WORDS = [
    // --- Easy (Short) ---
    { word: "neko", display: "猫", kana: "ねこ" },
    { word: "inu", display: "犬", kana: "いぬ" },
    { word: "sora", display: "空", kana: "そら" },
    { word: "umi", display: "海", kana: "うみ" },
    { word: "yume", display: "夢", kana: "ゆめ" },
    { word: "hana", display: "花", kana: "はな" },
    { word: "kaze", display: "風", kana: "かぜ" },
    { word: "niwa", display: "庭", kana: "にわ" },
    { word: "mado", display: "窓", kana: "まど" },
    { word: "kagi", display: "鍵", kana: "かぎ" },

    // --- Normal (Medium) ---
    { word: "ringo", display: "林檎", kana: "りんご" },
    { word: "mikan", display: "蜜柑", kana: "みかん" },
    { word: "sakura", display: "桜", kana: "さくら" },
    { word: "megane", display: "眼鏡", kana: "めがね" },
    { word: "keitai", display: "携帯", kana: "けいたい" },
    { word: "kamera", display: "カメラ", kana: "かめら" },
    { word: "rajio", display: "ラジオ", kana: "らじお" },
    { word: "piano", display: "ピアノ", kana: "ぴあの" },
    { word: "gitah", display: "ギター", kana: "ぎたー" }, // Extended romanization handling might be needed later
    { word: "gitaa", display: "ギター", kana: "ぎたー" },

    // --- Hard (Long / Complex) ---
    { word: "pasokon", display: "パソコン", kana: "ぱそこん" },
    { word: "intahnetsuto", display: "インターネット", kana: "いんたーねっと" },
    { word: "inta-netto", display: "インターネット", kana: "いんたーねっと" },
    { word: "shinkansen", display: "新幹線", kana: "しんかんせん" },
    { word: "reizouko", display: "冷蔵庫", kana: "れいぞうこ" },
    { word: "senpuki", display: "扇風機", kana: "せんぷうき" },
    { word: "kousaten", display: "交差点", kana: "こうさてん" },
    { word: "bijutsukan", display: "美術館", kana: "びじゅつかん" },
    { word: "suizokukan", display: "水族館", kana: "すいぞくかん" },
    { word: "doubutsuen", display: "動物園", kana: "どうぶつえん" },
    { word: "yuuenchi", display: "遊園地", kana: "ゆうえんち" },

    // --- Tech / Programming ---
    { word: "taipusukuriputo", display: "TypeScript", kana: "たいぷすくりぷと" },
    { word: "javasukuriputo", display: "JavaScript", kana: "じゃばすくりぷと" },
    { word: "ri-akuto", display: "React", kana: "りあくと" },
    { word: "nextojs", display: "Next.js", kana: "ねくすとじぇいえす" },
    { word: "faia-be-su", display: "Firebase", kana: "ふぁいあべーす" },
    { word: "kuraudofurea", display: "Cloudflare", kana: "くらうどふれあ" },

    // ====== 学校 ======
    { word: "kyoushitsu", display: "教室", kana: "きょうしつ" },
    { word: "kokuban", display: "黒板", kana: "こくばん" },
    { word: "enpitsu", display: "鉛筆", kana: "えんぴつ" },
    { word: "shukudai", display: "宿題", kana: "しゅくだい" },
    { word: "kyuushoku", display: "給食", kana: "きゅうしょく" },
    { word: "taiikukan", display: "体育館", kana: "たいいくかん" },
    { word: "undoukai", display: "運動会", kana: "うんどうかい" },
    { word: "bunkasai", display: "文化祭", kana: "ぶんかさい" },
    { word: "shuuyaku_ryokou", display: "修学旅行", kana: "しゅうがくりょこう" },
    { word: "sotsugyoushiki", display: "卒業式", kana: "そつぎょうしき" },

    // ====== 家・生活 ======
    { word: "genkan", display: "玄関", kana: "げんかん" },
    { word: "daidokoro", display: "台所", kana: "だいどころ" },
    { word: "furo", display: "風呂", kana: "ふろ" },
    { word: "shinshitsu", display: "寝室", kana: "しんしつ" },
    { word: "sentakuki", display: "洗濯機", kana: "せんたくき" },
    { word: "soujiki", display: "掃除機", kana: "そうじき" },
    { word: "suihanki", display: "炊飯器", kana: "すいはんき" },
    { word: "denshirenji", display: "電子レンジ", kana: "でんしれんじ" },
    { word: "haburashi", display: "歯ブラシ", kana: "はぶらし" },
    { word: "sekken", display: "石鹸", kana: "せっけん" },

    // ====== 料理 ======
    { word: "kare-raisu", display: "カレーライス", kana: "かれーらいす" },
    { word: "hanba-gu", display: "ハンバーグ", kana: "はんばーぐ" },
    { word: "omuraisu", display: "オムライス", kana: "おむらいす" },
    { word: "sushi", display: "寿司", kana: "すし" },
    { word: "tenpura", display: "天ぷら", kana: "てんぷら" },
    { word: "yakiniku", display: "焼き肉", kana: "やきにく" },
    { word: "ra-men", display: "ラーメン", kana: "らーめん" },
    { word: "udon", display: "うどん", kana: "うどん" },
    { word: "pasuta", display: "パスタ", kana: "ぱすた" },
    { word: "piza", display: "ピザ", kana: "ぴざ" },

    // ====== 職業 ======
    { word: "isha", display: "医者", kana: "いしゃ" },
    { word: "kangoshi", display: "看護師", kana: "かんごし" },
    { word: "keisatsukan", display: "警察官", kana: "けいさつかん" },
    { word: "shouboushi", display: "消防士", kana: "しょうぼうし" },
    { word: "pairotto", display: "パイロット", kana: "ぱいろっと" },
    { word: "sensei", display: "先生", kana: "せんせい" },
    { word: "kashu", display: "歌手", kana: "かしゅ" },
    { word: "haiyuu", display: "俳優", kana: "はいゆう" },
    { word: "seiyuu", display: "声優", kana: "せいゆう" },
    { word: "yuchuba", display: "YouTuber", kana: "ゆーちゅーばー" },

    // ====== 感情・様子 ======
    { word: "tanoshii", display: "楽しい", kana: "たのしい" },
    { word: "ureshii", display: "嬉しい", kana: "うれしい" },
    { word: "omoshiroi", display: "面白い", kana: "おもしろい" },
    { word: "utsukushii", display: "美しい", kana: "うつくしい" },
    { word: "muzukashii", display: "難しい", kana: "むずかしい" },
    { word: "kantan", display: "簡単", kana: "かんたん" },
    { word: "nemui", display: "眠い", kana: "ねむい" },
    { word: "subarashii", display: "素晴らしい", kana: "すばらしい" },
    { word: "natsukashii", display: "懐かしい", kana: "なつかしい" },
    { word: "hazukashii", display: "恥ずかしい", kana: "はずかしい" },

    // ====== 動詞 ======
    { word: "hashiru", display: "走る", kana: "はしる" },
    { word: "taberu", display: "食べる", kana: "たべる" },
    { word: "manabu", display: "学ぶ", kana: "まなぶ" },
    { word: "kangaeru", display: "考える", kana: "かんがえる" },
    { word: "warau", display: "笑う", kana: "わらう" },
    { word: "sagasu", display: "探す", kana: "さがす" },
    { word: "tsukuru", display: "作る", kana: "つくる" },
    { word: "asobu", display: "遊ぶ", kana: "あそぶ" },
    { word: "utau", display: "歌う", kana: "うたう" },
    { word: "oyogu", display: "泳ぐ", kana: "およぐ" },

    // ====== 自然・天気 ======
    { word: "taifuu", display: "台風", kana: "たいふう" },
    { word: "inazuma", display: "稲妻", kana: "いなずま" },
    { word: "niji", display: "虹", kana: "にじ" },
    { word: "o-rora", display: "オーロラ", kana: "おーろら" },
    { word: "mangetsu", display: "満月", kana: "まんげつ" },
    { word: "seiza", display: "星座", kana: "せいざ" },
    { word: "amanogawa", display: "天の川", kana: "あまのがわ" },
    { word: "sabaku", display: "砂漠", kana: "さばく" },
    { word: "kazan", display: "火山", kana: "かざん" },
    { word: "doukutsu", display: "洞窟", kana: "どうくつ" },

    // ====== IT用語 (追加) ======
    { word: "de-tabe-su", display: "データベース", kana: "でーたべーす" },
    { word: "arugorizumu", display: "アルゴリズム", kana: "あるごりずむ" },
    { word: "nettowa-ku", display: "ネットワーク", kana: "ねっとわーく" },
    { word: "sekyuriti", display: "セキュリティ", kana: "せきゅりてぃ" },
    { word: "debaggu", display: "デバッグ", kana: "でばっぐ" },
    { word: "kasoutsuuka", display: "仮想通貨", kana: "かそうつうか" },
    { word: "jinkouchinou", display: "人工知能", kana: "じんこうちのう" },
    { word: "burokkuche-n", display: "ブロックチェーン", kana: "ぶろっくちぇーん" },

    // ====== ことわざ・慣用句 ======
    { word: "ishinouenimosannen", display: "石の上にも三年", kana: "いしのうえにもさんねん" },
    { word: "sarumokikaraochiru", display: "猿も木から落ちる", kana: "さるもきからおちる" },
    { word: "chirimotsumorebayamatonaru", display: "塵も積もれば山となる", kana: "ちりもつもればやまとなる" },
    { word: "keizokuhachikararari", display: "継続は力なり", kana: "けいぞくはちからなり" },
    { word: "hanayoridango", display: "花より団子", kana: "はなよりだんご" },
    { word: "kappanokawanagare", display: "河童の川流れ", kana: "かっぱのかわながれ" },
    { word: "umanomimiminennbutsu", display: "馬の耳に念仏", kana: "うまのみみにねんぶつ" },
    { word: "makeinunotooboe", display: "負け犬の遠吠え", kana: "まけいぬのとおぼえ" },
    { word: "isogabamaware", display: "急がば回れ", kana: "いそがばまわれ" },
    { word: "amefuttejikatamarau", display: "雨降って地固まる", kana: "あめふってじかたまる" },
    { word: "hyakubunhaikkennishikazu", display: "百聞は一見にしかず", kana: "ひゃくぶんはいっけんにしかず" },
    { word: "nanakorobiyaoki", display: "七転び八起き", kana: "ななころびやおき" },
    { word: "mikkabouzu", display: "三日坊主", kana: "みっかぼうず" },
    { word: "tanakarabotamochi", display: "棚からぼたもち", kana: "たなからぼたもち" },
    { word: "ronnyorishouko", display: "論より証拠", kana: "ろんよりしょうこ" },
    { word: "annzuruyoriumugayasushi", display: "案ずるより産むが易し", kana: "あんずるよりうむがやすし" },
    { word: "korobanusaninotue", display: "転ばぬ先の杖", kana: "ころばぬさきのつえ" },
    { word: "hayaokihasanmonnnotoku", display: "早起きは三文の徳", kana: "はやおきはさんもんのとく" },
    { word: "oninikanabou", display: "鬼に金棒", kana: "おににかなぼう" },
    { word: "inonakanokawazutaikaioshirazu", display: "井の中の蛙大海を知らず", kana: "いのなかのかわずたいかいをしらず" },

    // ====== IT・テクノロジー（長文） ======
    { word: "purogramingugenngo", display: "プログラミング言語", kana: "ぷろぐらみんぐげんご" },
    { word: "obujekutoshikou", display: "オブジェクト指向", kana: "おぶじぇくとしこう" },
    { word: "kuraudokonpyu-tinngu", display: "クラウドコンピューティング", kana: "くらうどこんぴゅーてぃんぐ" },
    { word: "saiba-sekyurititaisaku", display: "サイバーセキュリティ対策", kana: "さいばーせきゅりてぃたいさく" },
    { word: "jinkouchinounoshinnka", display: "人工知能の進化", kana: "じんこうちのうのしんか" },
    { word: "de-tabe-sunosekkei", display: "データベースの設計", kana: "でーたべーすのせっけい" },
    { word: "sofutouea kaihatsu", display: "ソフトウェア開発", kana: "そふとうぇあかいはつ" },
    { word: "mashinra-ninngu", display: "マシンラーニング", kana: "ましんらーにんぐ" },
    { word: "di-pura-ninngu", display: "ディープラーニング", kana: "でぃーぷらーにんぐ" },
    { word: "fure-muwa-ku", display: "フレームワーク", kana: "ふれーむわーく" },
    { word: "o-punnso-su", display: "オープンソース", kana: "おーぷんそーす" },
    { word: "ba-jonnkanri", display: "バージョン管理", kana: "ばーじょんかんり" },
    { word: "ajairukaihatsu", display: "アジャイル開発", kana: "あじゃいるかいはつ" },

    // ====== 長めの一般語 ======
    { word: "todoufukenn", display: "都道府県", kana: "とどうふけん" },
    { word: "kokusairenngo", display: "国際連合", kana: "こくさいれんごう" },
    { word: "kannkyoumonnndai", display: "環境問題", kana: "かんきょうもんだい" },
    { word: "shoushikoureika", display: "少子高齢化", kana: "しょうしこうれいか" },
    { word: "shizennsaigai", display: "自然災害", kana: "しぜんさいがい" },
    { word: "chikyuuonndannka", display: "地球温暖化", kana: "ちきゅうおんだんか" },
    { word: "sennkyokatsudou", display: "選挙活動", kana: "せんきょかつどう" },
    { word: "gimukyouiku", display: "義務教育", kana: "ぎむきょういく" },
    { word: "saiseikanouenerugi-", display: "再生可能エネルギー", kana: "さいせいかのうえねるぎー" },
    { word: "jouhouritrashi-", display: "情報リテラシー", kana: "じょうほうりてらしー" },
    { word: "komyunike-shonnnouryoku", display: "コミュニケーション能力", kana: "こみゅにけーしょんのうりょく" },
    { word: "jizokukanounashakai", display: "持続可能な社会", kana: "じぞくかのうなしゃかい" },

    // ====== 趣味・文化 ======
    { word: "nihonnnodenntoubunnka", display: "日本の伝統文化", kana: "にほんのでんとうぶんか" },
    { word: "sekaiisann", display: "世界遺産", kana: "せかいいさん" },
    { word: "orinpikku", display: "オリンピック", kana: "おりんぴっく" },
    { word: "boranntiakatdudou", display: "ボランティア活動", kana: "ぼらんてぃあかつどう" },
    { word: "dokushokansoubun", display: "読書感想文", kana: "どくしょかんそうぶん" },
    { word: "bunkasainojunnbi", display: "文化祭の準備", kana: "ぶんかさいのじゅんび" },
    { word: "ge-mupurograminngu", display: "ゲームプログラミング", kana: "げーむぷろぐらみんぐ" },
    { word: "innta-netto", display: "インターネット", kana: "いんたーねっと" },
    { word: "suma-tofon", display: "スマートフォン", kana: "すまーとふぉん" },
    { word: "tatchiitaipinngu", display: "タッチタイピング", kana: "たっちたいぴんぐ" },
];
